### ISSUE TITLE
How to write a smart contract？

### ISSUE THREAD

**Issue by xieepp** [symbiont-io/assembly-sdk#1]
Hello, I am the developer of Hundsun, I want to know how to write a symbiont smart contract, and how to interact with it, have examples reference? Thank you so much!

**Comment by adamkrellenstein** [comment]
Hi! Writing a Symbiont smart contract is outside the scope of this SDK, which only deals with our distributed ledger API. Please contact me at adam.krellenstein@symbiont.io for more information about smart contract authorship for our platform.
